import test from 'node:test';
import assert from 'node:assert/strict';
import {freshness,filterShips,aggregateDays,validPosition,escapeHTML,safeURL,csvCell,number} from '../core.mjs';

test('missing values stay missing and a real zero stays zero',()=>{assert.equal(number(null),'—');assert.equal(number(undefined),'—');assert.equal(number(0),'0');});
test('old, failed, absent and future feeds are never called current',()=>{const now=Date.parse('2026-10-03T12:00:00Z');const f={ok:true,data:[],observedAt:'2026-10-03T11:30:00Z'};assert.equal(freshness(f,now),'updated');assert.equal(freshness({...f,lastFailure:{}},now),'cached');assert.equal(freshness({...f,observedAt:'2026-10-01'},now),'stale');assert.equal(freshness({...f,observedAt:'2026-10-04'},now),'clock mismatch');assert.equal(freshness({ok:false,data:null},now),'unavailable');});
test('filters combine search, commercial type, area and watchlist',()=>{const ships=[{name:'GULF ONE',mmsi:'100',ship_category:'Oil Tanker',zone:'persian_gulf'},{name:'GULF TWO',mmsi:'200',ship_category:'Bulk Carrier',zone:'gulf_of_oman'}];assert.equal(filterShips(ships,{query:'gulf',type:'tanker',watch:true,watched:['100']}).length,1);assert.equal(filterShips(ships,{query:'gulf',type:'tanker',zone:'gulf_of_oman'}).length,0);});
test('daily graph excludes in-strait rows from completed crossings',()=>{assert.deepEqual(aggregateDays([{day:'2026-10-01',direction:'inbound',count:2},{day:'2026-10-01',direction:'outbound',count:3},{day:'2026-10-01',direction:'in_strait',count:40}]),[{day:'2026-10-01',inbound:2,outbound:3}]);});
test('invalid and out-of-area coordinates do not become map markers',()=>{assert.equal(validPosition({latitude:null,longitude:56}),false);assert.equal(validPosition({latitude:26,longitude:56}),true);assert.equal(validPosition({latitude:0,longitude:0}),false);assert.equal(validPosition({latitude:NaN,longitude:56}),false);});
test('external titles, links and CSV cells cannot inject markup or formulas',()=>{assert.equal(escapeHTML('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.equal(safeURL('javascript:alert(1)'),'#');assert.equal(safeURL('https://example.org/'),'https://example.org/');assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('a,"b"'),'"a,""b"""');});
